### ISSUE TITLE
Can not use Ctrl+C

### ISSUE THREAD

**Issue by Geson-anko** [Geson-anko/JarvisEngine#165]
Pythonのmultiprocessing環境でKeyboardInterrupt(Ctrl+C)を送信すると、全てのPythonインタプリタに送信されてしまい、安全に終了することができません。
代わりのキーコマンドを設定する必要があります。
https://github.com/Geson-anko/JarvisEngine/issues/160#issue-1246111706

### Instead of Ctrl+C
- `<ctrl>+<shift>+q`
- `<alt>+q`

このコマンドは`engine_config.toml`から変更できるようにすることが望ましいでしょう。
```toml
[commands]
[commands.keyboard]
shutdown = "<ctrl>+<shift>+q"
```
